# Generated by Django 6.0.3 on 2026-03-31 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=False)),
                ('font', models.CharField(choices=[('inria-serif', 'Inria Serif'), ('inter', 'Inter'), ('roboto', 'Roboto'), ('plus-jakarta', 'Plus Jakarta Sans'), ('petrona', 'Petrona')], default='inria-serif', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
